name: pysolid
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - scikit-image
  - fortran-compiler    # A generic way to obtain the Fortran compiler across platforms through conda-forge channel
